apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mtd-data
spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi